version: '3.4'

services:
# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname
  kframework_service:
    image: k-framework-docker
    container_name: k-framework-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    #保持容器运行
    tty: true
    restart: always
    network_mode: "host"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           # count: 1
    #           capabilities: [gpu]